'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'pt-BR' | 'en' | 'es' | 'fr' | 'it' | 'de' | 'zh' | 'ja' | 'ru'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Header
    'nav.home': 'Início',
    'nav.team': 'Equipe',
    'nav.technology': 'Tecnologia',
    'nav.services': 'Serviços',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'Tecnologia Militar de Quebra de Criptografia e Recuperação Total de Contas',
    'hero.description': 'Desenvolvida pelos MELHORES programadores e especialistas em IA do mercado mundial, nossa tecnologia quântica é capaz de quebrar QUALQUER sistema de criptografia existente. Precisamos APENAS do seu @email, nome de usuário OU número de celular para recuperar 100% do acesso! Utilizada por governos e agências de inteligência globais, garantimos 99.9% de sucesso na recuperação TOTAL de suas contas. Recupere o acesso perdido com a mesma tecnologia de nível militar que protege nações inteiras!',
    'hero.requirement': '✓ Precisamos APENAS: @Email, Nome de Usuário OU Número de Celular',
    'hero.stat1': 'Taxa de Sucesso',
    'hero.stat2': 'Poder Computacional',
    'hero.stat3': 'Contas Recuperadas',
    
    // Team
    'team.title': 'Equipe de Classe Mundial',
    'team.subtitle': 'Nossos especialistas trabalharam nas principais empresas de tecnologia e instituições de pesquisa do mundo',
    'team.role.cto': 'Diretor de Tecnologia',
    'team.role.head-ai': 'Chefe de Pesquisa em IA',
    'team.role.senior-crypto': 'Engenheiro Sênior de Criptografia',
    'team.role.chief-security': 'Arquiteto Chefe de Segurança',
    'team.role.lead-quantum': 'Especialista Líder em Computação Quântica',
    'team.bio.rajesh': 'Ex-Pesquisador Líder de IA no Google. PhD em Computação Quântica pelo MIT. Mais de 15 anos em criptografia.',
    'team.bio.priya': 'Ex-Divisão de IA da Microsoft. Especializada em redes neurais e aprendizado de máquina. Publicou mais de 50 artigos de pesquisa.',
    'team.bio.vikram': 'Anteriormente na Amazon Web Services. Especialista em algoritmos de criptografia RSA e AES. 12 anos de experiência.',
    'team.bio.wei': 'Ex-Líder de Segurança em Nuvem da Alibaba. PhD em Cibersegurança pela Universidade Tsinghua. 18 anos na área.',
    'team.bio.li': 'Ex-Pesquisa Huawei. Pioneiro em criptografia quântica. Múltiplas patentes em algoritmos quânticos.',
    
    // Technology
    'tech.title': 'Nossa Tecnologia',
    'tech.subtitle': 'Infraestrutura de IA e computação quântica de ponta impulsionando análise criptográfica revolucionária',
    'tech.ai.title': 'Modelos de IA Avançados',
    'tech.ai.desc': 'Redes neurais proprietárias treinadas em bilhões de padrões de criptografia',
    'tech.quantum.title': 'Computação Quântica',
    'tech.quantum.desc': 'Aproveitando algoritmos quânticos para velocidade de processamento exponencial',
    'tech.distributed.title': 'Computação Distribuída',
    'tech.distributed.desc': '10 petabytes de poder computacional em data centers globais',
    'tech.pattern.title': 'Reconhecimento de Padrões',
    'tech.pattern.desc': 'Modelos de ML que identificam vulnerabilidades criptográficas',
    'tech.gpu.title': 'Aceleração GPU',
    'tech.gpu.desc': 'Milhares de GPUs trabalhando em paralelo para máxima eficiência',
    'tech.cloud.title': 'Infraestrutura em Nuvem',
    'tech.cloud.desc': 'Arquitetura escalável lidando com milhões de solicitações',
    'tech.how.title': 'Como Funciona Nossa Tecnologia de Quebra',
    'tech.step1.title': '1. Identificação Inicial Simples',
    'tech.step1.desc': 'Precisamos APENAS do seu @email, nome de usuário OU número de celular! Nossa IA treinada pelos melhores programadores do mundo localiza e mapeia TODOS os padrões de criptografia da sua conta usando algoritmos militares de aprendizado de máquina',
    'tech.step2.title': '2. Identificação de Vulnerabilidades',
    'tech.step2.desc': 'Redes neurais avançadas identificam e exploram QUALQUER vulnerabilidade criptográfica, garantindo acesso total aos dados protegidos',
    'tech.step3.title': '3. Quebra Quântica Instantânea',
    'tech.step3.desc': 'Supercomputadores quânticos processam MILHÕES de combinações por segundo, quebrando a criptografia em tempo recorde',
    'tech.step4.title': '4. Recuperação Total Garantida',
    'tech.step4.desc': 'Recuperamos 100% do acesso à sua conta com taxa de sucesso de 99.9%, devolvendo TOTAL controle sobre seus dados',
    
    // Services
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Quebra de criptografia e recuperação garantida de contas em TODAS as principais plataformas de redes sociais do mundo. Precisamos APENAS do @email, nome de usuário OU número de celular!',
    'services.requirement': 'Recuperação com apenas: @Email • Nome de Usuário • Número de Celular',
    'services.coming-soon': 'Em Breve',
    
    // WhatsApp Service
    'whatsapp.title': 'Quebra de Criptografia WhatsApp',
    'whatsapp.reviews': 'Avaliações de Usuários',
    'whatsapp.phone-label': 'Número do WhatsApp',
    'whatsapp.phone-placeholder': '(11) 98765-4321',
    'whatsapp.start': 'Iniciar Quebra de Senha',
    'whatsapp.description': 'Sistema militar de quebra de criptografia E2E para recuperação total de acesso ao WhatsApp',
    'whatsapp.confirm.title': 'Confirmar Conta WhatsApp',
    'whatsapp.confirm.message': 'Confirme se esta é a conta que deseja quebrar a criptografia e recuperar o acesso completo.',
    'whatsapp.confirm.yes': 'Confirmar e Iniciar',
    'whatsapp.confirm.no': 'Cancelar',
    'whatsapp.disclaimer': '⚠️ Simulador educacional. WhatsApp usa criptografia E2E que é matematicamente impossível de quebrar.',
    'whatsapp.analyzing': 'Quebrando Criptografia WhatsApp',
    'whatsapp.phase1': 'Conectando com IA Quântica',
    'whatsapp.phase2': 'Quebrando Criptografia E2E',
    'whatsapp.phase3': 'Descriptografando Dados',
    'whatsapp.phase4': 'Extraindo Conversas e Mídia',
    'whatsapp.phase5': 'Finalizando Acesso Total',
    'whatsapp.complete': 'Criptografia Quebrada com Sucesso',
    'whatsapp.conversations': 'Conversas',
    'whatsapp.images': 'Imagens',
    'whatsapp.videos': 'Vídeos',
    'whatsapp.privacy': 'Conteúdo borrado por privacidade',
    'whatsapp.download.title': 'Conteúdo Recuperado com Sucesso!',
    'whatsapp.download.description': 'Todos os dados foram descriptografados e estão prontos para download. O arquivo contém conversas, imagens e vídeos recuperados.',
    'whatsapp.download.button': 'Baixar Conteúdo Recuperado',
    'whatsapp.download.size': 'Tamanho estimado: 2.4 GB • Formato: ZIP criptografado',
    'whatsapp.new-analysis': 'Nova Análise',
    'whatsapp.back': 'Voltar',
    'whatsapp.validating': 'Validando número no WhatsApp...',
    'whatsapp.error.invalid': 'Número de telefone inválido. Digite apenas o número com DDD (ex: 11987654321).',
    'whatsapp.error.notfound': '❌ Este número NÃO está registrado no WhatsApp. Apenas números reais e ativos são aceitos.',
    
    // Terminal Commands
    'whatsapp.terminal.init': 'INIT',
    'whatsapp.terminal.connecting': 'Conectando ao servidor quântico...',
    'whatsapp.terminal.ok': 'OK',
    'whatsapp.terminal.connected': 'Conexão estabelecida com sucesso',
    'whatsapp.terminal.scan': 'SCAN',
    'whatsapp.terminal.mapping': 'Mapeando criptografia',
    'whatsapp.terminal.decrypt': 'DECRYPT',
    'whatsapp.terminal.breaking': 'Quebrando chave',
    'whatsapp.terminal.crack': 'CRACK',
    'whatsapp.terminal.testing': 'Testando',
    'whatsapp.terminal.combinations': 'combinações/s',
    'whatsapp.terminal.ai': 'AI',
    'whatsapp.terminal.analyzing': 'Analisando padrões neurais...',
    'whatsapp.terminal.quantum': 'QUANTUM',
    'whatsapp.terminal.processing': 'Processando',
    'whatsapp.terminal.break': 'BREAK',
    'whatsapp.terminal.vulnerability': 'Vulnerabilidade encontrada',
    'whatsapp.terminal.access': 'ACCESS',
    'whatsapp.terminal.decrypting': 'Descriptografando mensagens...',
    'whatsapp.terminal.extract': 'EXTRACT',
    'whatsapp.terminal.recovering': 'Recuperando',
    'whatsapp.terminal.conversations': 'conversas',
    'whatsapp.terminal.media': 'MEDIA',
    'whatsapp.terminal.extracting': 'Extraindo',
    'whatsapp.terminal.files': 'arquivos de mídia',
    'whatsapp.terminal.final': 'FINAL',
    'whatsapp.terminal.compiling': 'Compilando dados recuperados...',
    'whatsapp.terminal.success': 'SUCCESS',
    'whatsapp.terminal.totalaccess': 'Acesso total obtido com sucesso!',
    'whatsapp.terminal.complete': 'COMPLETE',
    'whatsapp.terminal.successrate': 'Taxa de sucesso',
    
    // Reviews
    'reviews.title': 'Avaliações de Clientes',
    'reviews.subtitle': 'Veja o que nossos clientes dizem sobre nossos serviços',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': 'Funcionou perfeitamente! Recuperei todas as minhas conversas antigas. Tecnologia incrível!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Serviço muito profissional. A equipe foi extremamente prestativa e o resultado superou minhas expectativas.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Impressionante tecnologia de IA. Consegui recuperar fotos antigas que pensei ter perdido para sempre.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Excelente serviço de recuperação de Gmail. Recuperei e-mails importantes de anos atrás.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Recuperei todas as minhas fotos do Instagram. O processo foi rápido e seguro. Recomendo!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'Consegui acessar mensagens antigas do Facebook. Equipe muito competente e atenciosa.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'Serviço de WhatsApp funcionou perfeitamente. Recuperei conversas de mais de 2 anos atrás!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'Análise do Telegram foi muito eficiente. Tecnologia de ponta com resultados impressionantes.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Excelente custo-benefício. Recuperei dados importantes do WhatsApp de forma rápida e segura.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Fornecedor líder de soluções de análise e recuperação criptográfica com IA.',
    'footer.quick-links': 'Links Rápidos',
    'footer.services': 'Serviços',
    'footer.contact': 'Contato',
    'footer.copyright': '© 2024 Redline Systems AI. Todos os direitos reservados.',
  },
  
  'en': {
    // Header
    'nav.home': 'Home',
    'nav.team': 'Team',
    'nav.technology': 'Technology',
    'nav.services': 'Services',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'Military-Grade Cryptography Breaking & Total Account Recovery Technology',
    'hero.description': 'Developed by the BEST programmers and AI specialists in the global market, our quantum technology can break ANY existing encryption system. We need ONLY your @email, username OR phone number to recover 100% access! Used by governments and global intelligence agencies, we guarantee 99.9% success in TOTAL account recovery. Regain lost access with the same military-grade technology that protects entire nations!',
    'hero.requirement': '✓ We need ONLY: @Email, Username OR Phone Number',
    'hero.stat1': 'Success Rate',
    'hero.stat2': 'Computing Power',
    'hero.stat3': 'Accounts Recovered',
    
    // Team
    'team.title': 'World-Class Team',
    'team.subtitle': 'Our experts have worked at the world\'s leading technology companies and research institutions',
    'team.role.cto': 'Chief Technology Officer',
    'team.role.head-ai': 'Head of AI Research',
    'team.role.senior-crypto': 'Senior Cryptography Engineer',
    'team.role.chief-security': 'Chief Security Architect',
    'team.role.lead-quantum': 'Lead Quantum Computing Specialist',
    'team.bio.rajesh': 'Former Lead AI Researcher at Google. PhD in Quantum Computing from MIT. 15+ years in cryptography.',
    'team.bio.priya': 'Ex-Microsoft AI Division. Specialized in neural networks and machine learning. Published 50+ research papers.',
    'team.bio.vikram': 'Previously at Amazon Web Services. Expert in RSA and AES encryption algorithms. 12 years experience.',
    'team.bio.wei': 'Former Alibaba Cloud Security Lead. PhD in Cybersecurity from Tsinghua University. 18 years in the field.',
    'team.bio.li': 'Ex-Huawei Research. Pioneer in quantum cryptography. Multiple patents in quantum algorithms.',
    
    // Technology
    'tech.title': 'Our Technology',
    'tech.subtitle': 'Cutting-edge AI and quantum computing infrastructure powering breakthrough cryptography analysis',
    'tech.ai.title': 'Advanced AI Models',
    'tech.ai.desc': 'Proprietary neural networks trained on billions of encryption patterns',
    'tech.quantum.title': 'Quantum Computing',
    'tech.quantum.desc': 'Leveraging quantum algorithms for exponential processing speed',
    'tech.distributed.title': 'Distributed Computing',
    'tech.distributed.desc': '10 petabytes of computing power across global data centers',
    'tech.pattern.title': 'Pattern Recognition',
    'tech.pattern.desc': 'ML models that identify cryptographic vulnerabilities',
    'tech.gpu.title': 'GPU Acceleration',
    'tech.gpu.desc': 'Thousands of GPUs working in parallel for maximum efficiency',
    'tech.cloud.title': 'Cloud Infrastructure',
    'tech.cloud.desc': 'Scalable architecture handling millions of requests',
    'tech.how.title': 'How Our Breaking Technology Works',
    'tech.step1.title': '1. Simple Initial Identification',
    'tech.step1.desc': 'We need ONLY your @email, username OR phone number! Our AI trained by the world\'s best programmers locates and maps ALL encryption patterns of your account using military-grade machine learning algorithms',
    'tech.step2.title': '2. Vulnerability Identification',
    'tech.step2.desc': 'Advanced neural networks identify and exploit ANY cryptographic vulnerability, ensuring total access to protected data',
    'tech.step3.title': '3. Instant Quantum Breaking',
    'tech.step3.desc': 'Quantum supercomputers process MILLIONS of combinations per second, breaking encryption in record time',
    'tech.step4.title': '4. Guaranteed Total Recovery',
    'tech.step4.desc': 'We recover 100% access to your account with 99.9% success rate, returning TOTAL control over your data',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Guaranteed cryptography breaking and account recovery on ALL major social media platforms worldwide. We need ONLY your @email, username OR phone number!',
    'services.requirement': 'Recovery with only: @Email • Username • Phone Number',
    'services.coming-soon': 'Coming Soon',
    
    // WhatsApp Service
    'whatsapp.title': 'WhatsApp Cryptography Breaking',
    'whatsapp.reviews': 'User Reviews',
    'whatsapp.phone-label': 'WhatsApp Number',
    'whatsapp.phone-placeholder': '(415) 555-2671',
    'whatsapp.start': 'Start Password Breaking',
    'whatsapp.description': 'Military-grade E2E cryptography breaking system for total WhatsApp access recovery',
    'whatsapp.confirm.title': 'Confirm WhatsApp Account',
    'whatsapp.confirm.message': 'Confirm if this is the account you want to break the encryption and recover full access.',
    'whatsapp.confirm.yes': 'Confirm and Start',
    'whatsapp.confirm.no': 'Cancel',
    'whatsapp.disclaimer': '⚠️ Educational simulator. WhatsApp uses E2E encryption that is mathematically impossible to break.',
    'whatsapp.analyzing': 'Breaking WhatsApp Encryption',
    'whatsapp.phase1': 'Connecting to Quantum AI',
    'whatsapp.phase2': 'Breaking E2E Encryption',
    'whatsapp.phase3': 'Decrypting Data',
    'whatsapp.phase4': 'Extracting Conversations & Media',
    'whatsapp.phase5': 'Finalizing Total Access',
    'whatsapp.complete': 'Encryption Successfully Broken',
    'whatsapp.conversations': 'Conversations',
    'whatsapp.images': 'Images',
    'whatsapp.videos': 'Videos',
    'whatsapp.privacy': 'Content blurred for privacy',
    'whatsapp.download.title': 'Content Successfully Recovered!',
    'whatsapp.download.description': 'All data has been decrypted and is ready for download. The file contains recovered conversations, images and videos.',
    'whatsapp.download.button': 'Download Recovered Content',
    'whatsapp.download.size': 'Estimated size: 2.4 GB • Format: Encrypted ZIP',
    'whatsapp.new-analysis': 'New Analysis',
    'whatsapp.back': 'Back',
    'whatsapp.validating': 'Validating number on WhatsApp...',
    'whatsapp.error.invalid': 'Invalid phone number. Enter only the number with area code (e.g., 4155552671).',
    'whatsapp.error.notfound': '❌ This number is NOT registered on WhatsApp. Only real and active numbers are accepted.',
    
    // Terminal Commands
    'whatsapp.terminal.init': 'INIT',
    'whatsapp.terminal.connecting': 'Connecting to quantum server...',
    'whatsapp.terminal.ok': 'OK',
    'whatsapp.terminal.connected': 'Connection established successfully',
    'whatsapp.terminal.scan': 'SCAN',
    'whatsapp.terminal.mapping': 'Mapping encryption',
    'whatsapp.terminal.decrypt': 'DECRYPT',
    'whatsapp.terminal.breaking': 'Breaking key',
    'whatsapp.terminal.crack': 'CRACK',
    'whatsapp.terminal.testing': 'Testing',
    'whatsapp.terminal.combinations': 'combinations/s',
    'whatsapp.terminal.ai': 'AI',
    'whatsapp.terminal.analyzing': 'Analyzing neural patterns...',
    'whatsapp.terminal.quantum': 'QUANTUM',
    'whatsapp.terminal.processing': 'Processing',
    'whatsapp.terminal.break': 'BREAK',
    'whatsapp.terminal.vulnerability': 'Vulnerability found',
    'whatsapp.terminal.access': 'ACCESS',
    'whatsapp.terminal.decrypting': 'Decrypting messages...',
    'whatsapp.terminal.extract': 'EXTRACT',
    'whatsapp.terminal.recovering': 'Recovering',
    'whatsapp.terminal.conversations': 'conversations',
    'whatsapp.terminal.media': 'MEDIA',
    'whatsapp.terminal.extracting': 'Extracting',
    'whatsapp.terminal.files': 'media files',
    'whatsapp.terminal.final': 'FINAL',
    'whatsapp.terminal.compiling': 'Compiling recovered data...',
    'whatsapp.terminal.success': 'SUCCESS',
    'whatsapp.terminal.totalaccess': 'Total access obtained successfully!',
    'whatsapp.terminal.complete': 'COMPLETE',
    'whatsapp.terminal.successrate': 'Success rate',
    
    // Reviews
    'reviews.title': 'Customer Reviews',
    'reviews.subtitle': 'See what our customers say about our services',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': 'Worked perfectly! Recovered all my old conversations. Amazing technology!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Very professional service. The team was extremely helpful and the result exceeded my expectations.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Impressive AI technology. I managed to recover old photos I thought were lost forever.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Excellent Gmail recovery service. Recovered important emails from years ago.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Recovered all my Instagram photos. The process was fast and secure. Highly recommend!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'Managed to access old Facebook messages. Very competent and attentive team.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'WhatsApp service worked perfectly. Recovered conversations from over 2 years ago!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'Telegram analysis was very efficient. Cutting-edge technology with impressive results.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Excellent value for money. Recovered important WhatsApp data quickly and securely.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Leading provider of AI-powered cryptography analysis and recovery solutions.',
    'footer.quick-links': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2024 Redline Systems AI. All rights reserved.',
  },
  
  'es': {
    // Header
    'nav.home': 'Inicio',
    'nav.team': 'Equipo',
    'nav.technology': 'Tecnología',
    'nav.services': 'Servicios',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'Tecnología Militar de Ruptura de Criptografía y Recuperación Total de Cuentas',
    'hero.description': 'Desarrollada por los MEJORES programadores y especialistas en IA del mercado mundial, nuestra tecnología cuántica puede romper CUALQUIER sistema de cifrado existente. ¡Necesitamos SOLO su @email, nombre de usuario O número de teléfono para recuperar el 100% del acceso! Utilizada por gobiernos y agencias de inteligencia globales, garantizamos 99.9% de éxito en la recuperación TOTAL de sus cuentas. ¡Recupere el acceso perdido con la misma tecnología de nivel militar que protege naciones enteras!',
    'hero.requirement': '✓ Necesitamos SOLO: @Email, Nombre de Usuario O Número de Teléfono',
    'hero.stat1': 'Tasa de Éxito',
    'hero.stat2': 'Poder Computacional',
    'hero.stat3': 'Cuentas Recuperadas',
    
    // Team
    'team.title': 'Equipo de Clase Mundial',
    'team.subtitle': 'Nuestros expertos han trabajado en las principales empresas tecnológicas e instituciones de investigación del mundo',
    'team.role.cto': 'Director de Tecnología',
    'team.role.head-ai': 'Jefe de Investigación en IA',
    'team.role.senior-crypto': 'Ingeniero Senior de Criptografía',
    'team.role.chief-security': 'Arquitecto Jefe de Seguridad',
    'team.role.lead-quantum': 'Especialista Líder en Computación Cuántica',
    'team.bio.rajesh': 'Ex-Investigador Líder de IA en Google. PhD en Computación Cuántica del MIT. Más de 15 años en criptografía.',
    'team.bio.priya': 'Ex-División de IA de Microsoft. Especializada en redes neuronales y aprendizaje automático. Publicó más de 50 artículos de investigación.',
    'team.bio.vikram': 'Anteriormente en Amazon Web Services. Experto en algoritmos de cifrado RSA y AES. 12 años de experiencia.',
    'team.bio.wei': 'Ex-Líder de Seguridad en la Nube de Alibaba. PhD en Ciberseguridad de la Universidad Tsinghua. 18 años en el campo.',
    'team.bio.li': 'Ex-Investigación Huawei. Pionero en criptografía cuántica. Múltiples patentes en algoritmos cuánticos.',
    
    // Technology
    'tech.title': 'Nuestra Tecnología',
    'tech.subtitle': 'Infraestructura de IA y computación cuántica de vanguardia impulsando análisis criptográfico revolucionario',
    'tech.ai.title': 'Modelos de IA Avanzados',
    'tech.ai.desc': 'Redes neuronales propietarias entrenadas en miles de millones de patrones de cifrado',
    'tech.quantum.title': 'Computación Cuántica',
    'tech.quantum.desc': 'Aprovechando algoritmos cuánticos para velocidad de procesamiento exponencial',
    'tech.distributed.title': 'Computación Distribuida',
    'tech.distributed.desc': '10 petabytes de poder computacional en centros de datos globales',
    'tech.pattern.title': 'Reconocimiento de Patrones',
    'tech.pattern.desc': 'Modelos de ML que identifican vulnerabilidades criptográficas',
    'tech.gpu.title': 'Aceleración GPU',
    'tech.gpu.desc': 'Miles de GPUs trabajando en paralelo para máxima eficiencia',
    'tech.cloud.title': 'Infraestructura en la Nube',
    'tech.cloud.desc': 'Arquitectura escalable manejando millones de solicitudes',
    'tech.how.title': 'Cómo Funciona',
    'tech.step1.title': 'Adquisición de Datos',
    'tech.step1.desc': 'Nuestros sistemas de IA analizan patrones de datos cifrados usando algoritmos avanzados de aprendizaje automático',
    'tech.step2.title': 'Análisis de Patrones',
    'tech.step2.desc': 'Las redes neuronales identifican patrones criptográficos y vulnerabilidades potenciales',
    'tech.step3.title': 'Procesamiento Cuántico',
    'tech.step3.desc': 'Los algoritmos cuánticos procesan millones de posibilidades simultáneamente',
    'tech.step4.title': 'Recuperación de Datos',
    'tech.step4.desc': 'Descifrar y recuperar datos exitosamente con una tasa de precisión del 99,9%',
    
    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Análisis criptográfico avanzado para todas las plataformas principales',
    'services.coming-soon': 'Próximamente',
    
    // WhatsApp Service
    'whatsapp.title': 'Análisis WhatsApp',
    'whatsapp.reviews': 'Reseñas de Usuarios',
    'whatsapp.phone-label': 'Número de WhatsApp',
    'whatsapp.phone-placeholder': '612 345 678',
    'whatsapp.start': 'Iniciar Análisis',
    'whatsapp.disclaimer': '⚠️ Simulador educacional. WhatsApp usa cifrado E2E que es matemáticamente imposible de romper.',
    'whatsapp.analyzing': 'Análisis en Progreso',
    'whatsapp.phase1': 'Conectando con IA',
    'whatsapp.phase2': 'Analizando Cifrado',
    'whatsapp.phase3': 'Escaneando Datos',
    'whatsapp.phase4': 'Clasificando Contenido',
    'whatsapp.phase5': 'Generando Resultados',
    'whatsapp.complete': 'Análisis Completo',
    'whatsapp.conversations': 'Conversaciones',
    'whatsapp.images': 'Imágenes',
    'whatsapp.videos': 'Videos',
    'whatsapp.privacy': 'Contenido difuminado por privacidad',
    'whatsapp.notice.title': 'Aviso Educacional',
    'whatsapp.notice.text1': 'Este es un simulador educacional que demuestra conceptos de seguridad. WhatsApp usa cifrado de extremo a extremo (E2E) que es matemáticamente imposible de romper.',
    'whatsapp.notice.text2': 'No se accedió ni comprometió ningún dato real. Esto es puramente un ejercicio educativo.',
    'whatsapp.new-analysis': 'Nuevo Análisis',
    'whatsapp.back': 'Volver',
    'whatsapp.validating': 'Validando número en WhatsApp...',
    'whatsapp.error.invalid': 'Número de teléfono inválido. Ingrese solo el número (ej: 612345678).',
    'whatsapp.error.notfound': '❌ Este número NO está registrado en WhatsApp. Solo se aceptan números reales y activos.',
    
    // Reviews
    'reviews.title': 'Reseñas de Clientes',
    'reviews.subtitle': 'Vea lo que dicen nuestros clientes sobre nuestros servicios',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': '¡Funcionó perfectamente! Recuperé todas mis conversaciones antiguas. ¡Tecnología increíble!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Servicio muy profesional. El equipo fue extremadamente útil y el resultado superó mis expectativas.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Impresionante tecnología de IA. Logré recuperar fotos antiguas que pensé que estaban perdidas para siempre.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Excelente servicio de recuperación de Gmail. Recuperé correos importantes de hace años.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Recuperé todas mis fotos de Instagram. El proceso fue rápido y seguro. ¡Lo recomiendo!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'Logré acceder a mensajes antiguos de Facebook. Equipo muy competente y atento.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'El servicio de WhatsApp funcionó perfectamente. ¡Recuperé conversaciones de hace más de 2 años!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'El análisis de Telegram fue muy eficiente. Tecnología de vanguardia con resultados impresionantes.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Excelente relación calidad-precio. Recuperé datos importantes de WhatsApp de forma rápida y segura.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Proveedor líder de soluciones de análisis y recuperación criptográfica con IA.',
    'footer.quick-links': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.contact': 'Contacto',
    'footer.copyright': '© 2024 Redline Systems AI. Todos los derechos reservados.',
  },
  
  'fr': {
    // Header
    'nav.home': 'Accueil',
    'nav.team': 'Équipe',
    'nav.technology': 'Technologie',
    'nav.services': 'Services',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'La Technologie la Plus Avancée en Cassage de Cryptographie et Récupération de Comptes',
    'hero.description': 'Nous pouvons casser N\'IMPORTE QUEL système de cryptage et récupérer l\'accès à TOUS vos comptes de réseaux sociaux! Notre technologie IA quantique, utilisée par les gouvernements et agences de renseignement du monde entier, garantit 99.9% de succès dans la récupération de données. Récupérez vos comptes perdus avec la même technologie qui protège les nations!',
    'hero.stat1': 'Taux de Réussite',
    'hero.stat2': 'Puissance de Calcul',
    'hero.stat3': 'Comptes Récupérés',
    
    // Team
    'team.title': 'Équipe de Classe Mondiale',
    'team.subtitle': 'Nos experts ont travaillé dans les principales entreprises technologiques et institutions de recherche du monde',
    'team.role.cto': 'Directeur de la Technologie',
    'team.role.head-ai': 'Chef de la Recherche en IA',
    'team.role.senior-crypto': 'Ingénieur Senior en Cryptographie',
    'team.role.chief-security': 'Architecte en Chef de la Sécurité',
    'team.role.lead-quantum': 'Spécialiste Principal en Informatique Quantique',
    'team.bio.rajesh': 'Ancien chercheur principal en IA chez Google. PhD en informatique quantique du MIT. Plus de 15 ans en cryptographie.',
    'team.bio.priya': 'Ex-Division IA de Microsoft. Spécialisée dans les réseaux neuronaux et l\'apprentissage automatique. A publié plus de 50 articles de recherche.',
    'team.bio.vikram': 'Précédemment chez Amazon Web Services. Expert en algorithmes de chiffrement RSA et AES. 12 ans d\'expérience.',
    'team.bio.wei': 'Ancien responsable de la sécurité cloud d\'Alibaba. PhD en cybersécurité de l\'Université Tsinghua. 18 ans dans le domaine.',
    'team.bio.li': 'Ex-Recherche Huawei. Pioneer en cryptographie quantique. Plusieurs brevets en algorithmes quantiques.',
    
    // Technology
    'tech.title': 'Notre Technologie',
    'tech.subtitle': 'Infrastructure d\'IA et d\'informatique quantique de pointe alimentant une analyse cryptographique révolutionnaire',
    'tech.ai.title': 'Modèles d\'IA Avancés',
    'tech.ai.desc': 'Réseaux neuronaux propriétaires formés sur des milliards de modèles de chiffrement',
    'tech.quantum.title': 'Informatique Quantique',
    'tech.quantum.desc': 'Exploitation d\'algorithmes quantiques pour une vitesse de traitement exponentielle',
    'tech.distributed.title': 'Informatique Distribuée',
    'tech.distributed.desc': '10 pétaoctets de puissance de calcul dans les centres de données mondiaux',
    'tech.pattern.title': 'Reconnaissance de Motifs',
    'tech.pattern.desc': 'Modèles ML qui identifient les vulnérabilités cryptographiques',
    'tech.gpu.title': 'Accélération GPU',
    'tech.gpu.desc': 'Des milliers de GPU travaillant en parallèle pour une efficacité maximale',
    'tech.cloud.title': 'Infrastructure Cloud',
    'tech.cloud.desc': 'Architecture évolutive gérant des millions de requêtes',
    'tech.how.title': 'Comment Ça Marche',
    'tech.step1.title': 'Acquisition de Données',
    'tech.step1.desc': 'Nos systèmes d\'IA analysent les modèles de données chiffrées à l\'aide d\'algorithmes d\'apprentissage automatique avancés',
    'tech.step2.title': 'Analyse de Motifs',
    'tech.step2.desc': 'Les réseaux neuronaux identifient les modèles cryptographiques et les vulnérabilités potentielles',
    'tech.step3.title': 'Traitement Quantique',
    'tech.step3.desc': 'Les algorithmes quantiques traitent des millions de possibilités simultanément',
    'tech.step4.title': 'Récupération de Données',
    'tech.step4.desc': 'Déchiffrer et récupérer avec succès les données avec un taux de précision de 99,9%',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Analyse cryptographique avancée pour toutes les principales plateformes',
    'services.coming-soon': 'Bientôt Disponible',
    
    // WhatsApp Service
    'whatsapp.title': 'Analyse WhatsApp',
    'whatsapp.reviews': 'Avis des Utilisateurs',
    'whatsapp.phone-label': 'Numéro WhatsApp',
    'whatsapp.phone-placeholder': '+33 6 12 34 56 78',
    'whatsapp.start': 'Démarrer l\'Analyse',
    'whatsapp.disclaimer': '⚠️ Simulateur éducatif. WhatsApp utilise le chiffrement E2E qui est mathématiquement impossible à casser.',
    'whatsapp.analyzing': 'Analyse en Cours',
    'whatsapp.phase1': 'Connexion à l\'IA',
    'whatsapp.phase2': 'Analyse du Chiffrement',
    'whatsapp.phase3': 'Scan des Données',
    'whatsapp.phase4': 'Classification du Contenu',
    'whatsapp.phase5': 'Génération des Résultats',
    'whatsapp.complete': 'Analyse Terminée',
    'whatsapp.conversations': 'Conversations',
    'whatsapp.images': 'Images',
    'whatsapp.videos': 'Vidéos',
    'whatsapp.privacy': 'Contenu flouté pour la confidentialité',
    'whatsapp.notice.title': 'Avis Éducatif',
    'whatsapp.notice.text1': 'Ceci est un simulateur éducatif démontrant des concepts de sécurité. WhatsApp utilise le chiffrement de bout en bout (E2E) qui est mathématiquement impossible à casser.',
    'whatsapp.notice.text2': 'Aucune donnée réelle n\'a été consultée ou compromise. Ceci est purement un exercice éducatif.',
    'whatsapp.new-analysis': 'Nouvelle Analyse',
    'whatsapp.back': 'Retour',
    
    // Reviews
    'reviews.title': 'Avis des Clients',
    'reviews.subtitle': 'Découvrez ce que nos clients disent de nos services',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': 'Fonctionné parfaitement! J\'ai récupéré toutes mes anciennes conversations. Technologie incroyable!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Service très professionnel. L\'équipe a été extrêmement serviable et le résultat a dépassé mes attentes.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Technologie IA impressionnante. J\'ai réussi à récupérer d\'anciennes photos que je pensais perdues à jamais.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Excellent service de récupération Gmail. J\'ai récupéré des e-mails importants d\'il y a des années.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'J\'ai récupéré toutes mes photos Instagram. Le processus était rapide et sécurisé. Je recommande!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'J\'ai réussi à accéder aux anciens messages Facebook. Équipe très compétente et attentive.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'Le service WhatsApp a parfaitement fonctionné. J\'ai récupéré des conversations de plus de 2 ans!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'L\'analyse Telegram était très efficace. Technologie de pointe avec des résultats impressionnants.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Excellent rapport qualité-prix. J\'ai récupéré des données WhatsApp importantes rapidement et en toute sécurité.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Fournisseur leader de solutions d\'analyse et de récupération cryptographique alimentées par l\'IA.',
    'footer.quick-links': 'Liens Rapides',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2024 Redline Systems AI. Tous droits réservés.',
  },
  
  'it': {
    // Header
    'nav.home': 'Home',
    'nav.team': 'Team',
    'nav.technology': 'Tecnologia',
    'nav.services': 'Servizi',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'La Tecnologia Più Avanzata nella Rottura della Crittografia e Recupero Account',
    'hero.description': 'Possiamo violare QUALSIASI sistema di crittografia e recuperare l\'accesso a TUTTI i tuoi account di social media! La nostra tecnologia IA quantistica, utilizzata da governi e agenzie di intelligence in tutto il mondo, garantisce il 99.9% di successo nel recupero dati. Recupera i tuoi account persi con la stessa tecnologia che protegge le nazioni!',
    'hero.stat1': 'Tasso di Successo',
    'hero.stat2': 'Potenza di Calcolo',
    'hero.stat3': 'Account Recuperati',
    
    // Team
    'team.title': 'Team di Classe Mondiale',
    'team.subtitle': 'I nostri esperti hanno lavorato nelle principali aziende tecnologiche e istituzioni di ricerca del mondo',
    'team.role.cto': 'Direttore Tecnologico',
    'team.role.head-ai': 'Responsabile Ricerca IA',
    'team.role.senior-crypto': 'Ingegnere Senior Crittografia',
    'team.role.chief-security': 'Architetto Capo della Sicurezza',
    'team.role.lead-quantum': 'Specialista Leader Calcolo Quantistico',
    'team.bio.rajesh': 'Ex-Ricercatore Principale IA presso Google. PhD in Calcolo Quantistico dal MIT. Oltre 15 anni in crittografia.',
    'team.bio.priya': 'Ex-Divisione IA Microsoft. Specializzata in reti neurali e machine learning. Pubblicati oltre 50 articoli di ricerca.',
    'team.bio.vikram': 'Precedentemente presso Amazon Web Services. Esperto in algoritmi di crittografia RSA e AES. 12 anni di esperienza.',
    'team.bio.wei': 'Ex-Responsabile Sicurezza Cloud Alibaba. PhD in Cybersecurity dall\'Università Tsinghua. 18 anni nel settore.',
    'team.bio.li': 'Ex-Ricerca Huawei. Pioniere nella crittografia quantistica. Molteplici brevetti in algoritmi quantistici.',
    
    // Technology
    'tech.title': 'La Nostra Tecnologia',
    'tech.subtitle': 'Infrastruttura all\'avanguardia di IA e calcolo quantistico che alimenta l\'analisi crittografica rivoluzionaria',
    'tech.ai.title': 'Modelli IA Avanzati',
    'tech.ai.desc': 'Reti neurali proprietarie addestrate su miliardi di pattern di crittografia',
    'tech.quantum.title': 'Calcolo Quantistico',
    'tech.quantum.desc': 'Sfruttamento di algoritmi quantistici per velocità di elaborazione esponenziale',
    'tech.distributed.title': 'Calcolo Distribuito',
    'tech.distributed.desc': '10 petabyte di potenza di calcolo nei data center globali',
    'tech.pattern.title': 'Riconoscimento Pattern',
    'tech.pattern.desc': 'Modelli ML che identificano vulnerabilità crittografiche',
    'tech.gpu.title': 'Accelerazione GPU',
    'tech.gpu.desc': 'Migliaia di GPU che lavorano in parallelo per la massima efficienza',
    'tech.cloud.title': 'Infrastruttura Cloud',
    'tech.cloud.desc': 'Architettura scalabile che gestisce milioni di richieste',
    'tech.how.title': 'Come Funziona',
    'tech.step1.title': 'Acquisizione Dati',
    'tech.step1.desc': 'I nostri sistemi IA analizzano pattern di dati crittografati utilizzando algoritmi avanzati di machine learning',
    'tech.step2.title': 'Analisi Pattern',
    'tech.step2.desc': 'Le reti neurali identificano pattern crittografici e potenziali vulnerabilità',
    'tech.step3.title': 'Elaborazione Quantistica',
    'tech.step3.desc': 'Gli algoritmi quantistici elaborano milioni di possibilità simultaneamente',
    'tech.step4.title': 'Recupero Dati',
    'tech.step4.desc': 'Decrittare e recuperare con successo i dati con un tasso di precisione del 99,9%',
    
    // Services
    'services.title': 'I Nostri Servizi',
    'services.subtitle': 'Analisi crittografica avanzata per tutte le principali piattaforme',
    'services.coming-soon': 'Prossimamente',
    
    // WhatsApp Service
    'whatsapp.title': 'Analisi WhatsApp',
    'whatsapp.reviews': 'Recensioni Utenti',
    'whatsapp.phone-label': 'Numero WhatsApp',
    'whatsapp.phone-placeholder': '+39 333 123 4567',
    'whatsapp.start': 'Avvia Analisi',
    'whatsapp.disclaimer': '⚠️ Simulatore educativo. WhatsApp utilizza crittografia E2E matematicamente impossibile da violare.',
    'whatsapp.analyzing': 'Analisi in Corso',
    'whatsapp.phase1': 'Connessione all\'IA',
    'whatsapp.phase2': 'Analisi Crittografia',
    'whatsapp.phase3': 'Scansione Dati',
    'whatsapp.phase4': 'Classificazione Contenuto',
    'whatsapp.phase5': 'Generazione Risultati',
    'whatsapp.complete': 'Analisi Completata',
    'whatsapp.conversations': 'Conversazioni',
    'whatsapp.images': 'Immagini',
    'whatsapp.videos': 'Video',
    'whatsapp.privacy': 'Contenuto sfocato per privacy',
    'whatsapp.notice.title': 'Avviso Educativo',
    'whatsapp.notice.text1': 'Questo è un simulatore educativo che dimostra concetti di sicurezza. WhatsApp utilizza crittografia end-to-end (E2E) matematicamente impossibile da violare.',
    'whatsapp.notice.text2': 'Nessun dato reale è stato consultato o compromesso. Questo è puramente un esercizio educativo.',
    'whatsapp.new-analysis': 'Nuova Analisi',
    'whatsapp.back': 'Indietro',
    
    // Reviews
    'reviews.title': 'Recensioni Clienti',
    'reviews.subtitle': 'Scopri cosa dicono i nostri clienti dei nostri servizi',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': 'Funzionato perfettamente! Ho recuperato tutte le mie vecchie conversazioni. Tecnologia incredibile!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Servizio molto professionale. Il team è stato estremamente disponibile e il risultato ha superato le mie aspettative.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Tecnologia IA impressionante. Sono riuscito a recuperare vecchie foto che pensavo fossero perse per sempre.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Eccellente servizio di recupero Gmail. Ho recuperato email importanti di anni fa.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Ho recuperato tutte le mie foto di Instagram. Il processo è stato veloce e sicuro. Lo consiglio!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'Sono riuscita ad accedere a vecchi messaggi di Facebook. Team molto competente e attento.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'Il servizio WhatsApp ha funzionato perfettamente. Ho recuperato conversazioni di oltre 2 anni fa!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'L\'analisi di Telegram è stata molto efficiente. Tecnologia all\'avanguardia con risultati impressionanti.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Eccellente rapporto qualità-prezzo. Ho recuperato dati WhatsApp importanti in modo rapido e sicuro.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Fornitore leader di soluzioni di analisi e recupero crittografico alimentate da IA.',
    'footer.quick-links': 'Link Rapidi',
    'footer.services': 'Servizi',
    'footer.contact': 'Contatto',
    'footer.copyright': '© 2024 Redline Systems AI. Tutti i diritti riservati.',
  },
  
  'de': {
    // Header
    'nav.home': 'Startseite',
    'nav.team': 'Team',
    'nav.technology': 'Technologie',
    'nav.services': 'Dienstleistungen',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'Die Fortschrittlichste Technologie zum Knacken von Verschlüsselung und Konto-Wiederherstellung',
    'hero.description': 'Wir können JEDES Verschlüsselungssystem knacken und den Zugriff auf ALLE Ihre Social-Media-Konten wiederherstellen! Unsere Quanten-KI-Technologie, die von Regierungen und Geheimdiensten weltweit eingesetzt wird, garantiert 99.9% Erfolg bei der Datenwiederherstellung. Stellen Sie Ihre verlorenen Konten mit derselben Technologie wieder her, die Nationen schützt!',
    'hero.stat1': 'Erfolgsquote',
    'hero.stat2': 'Rechenleistung',
    'hero.stat3': 'Konten Wiederhergestellt',
    
    // Team
    'team.title': 'Weltklasse-Team',
    'team.subtitle': 'Unsere Experten haben bei den weltweit führenden Technologieunternehmen und Forschungseinrichtungen gearbeitet',
    'team.role.cto': 'Technischer Direktor',
    'team.role.head-ai': 'Leiter KI-Forschung',
    'team.role.senior-crypto': 'Senior Kryptographie-Ingenieur',
    'team.role.chief-security': 'Chefarchitekt Sicherheit',
    'team.role.lead-quantum': 'Leitender Quantencomputing-Spezialist',
    'team.bio.rajesh': 'Ehemaliger leitender KI-Forscher bei Google. PhD in Quantencomputing vom MIT. Über 15 Jahre in Kryptographie.',
    'team.bio.priya': 'Ex-Microsoft KI-Abteilung. Spezialisiert auf neuronale Netze und maschinelles Lernen. Über 50 Forschungsarbeiten veröffentlicht.',
    'team.bio.vikram': 'Zuvor bei Amazon Web Services. Experte für RSA- und AES-Verschlüsselungsalgorithmen. 12 Jahre Erfahrung.',
    'team.bio.wei': 'Ehemaliger Alibaba Cloud-Sicherheitsleiter. PhD in Cybersicherheit von der Tsinghua-Universität. 18 Jahre im Bereich.',
    'team.bio.li': 'Ex-Huawei-Forschung. Pionier in Quantenkryptographie. Mehrere Patente in Quantenalgorithmen.',
    
    // Technology
    'tech.title': 'Unsere Technologie',
    'tech.subtitle': 'Modernste KI- und Quantencomputing-Infrastruktur für bahnbrechende Kryptographie-Analyse',
    'tech.ai.title': 'Fortgeschrittene KI-Modelle',
    'tech.ai.desc': 'Proprietäre neuronale Netze, trainiert auf Milliarden von Verschlüsselungsmustern',
    'tech.quantum.title': 'Quantencomputing',
    'tech.quantum.desc': 'Nutzung von Quantenalgorithmen für exponentielle Verarbeitungsgeschwindigkeit',
    'tech.distributed.title': 'Verteiltes Computing',
    'tech.distributed.desc': '10 Petabyte Rechenleistung in globalen Rechenzentren',
    'tech.pattern.title': 'Mustererkennung',
    'tech.pattern.desc': 'ML-Modelle, die kryptographische Schwachstellen identifizieren',
    'tech.gpu.title': 'GPU-Beschleunigung',
    'tech.gpu.desc': 'Tausende von GPUs arbeiten parallel für maximale Effizienz',
    'tech.cloud.title': 'Cloud-Infrastruktur',
    'tech.cloud.desc': 'Skalierbare Architektur für Millionen von Anfragen',
    'tech.how.title': 'Wie Es Funktioniert',
    'tech.step1.title': 'Datenerfassung',
    'tech.step1.desc': 'Unsere KI-Systeme analysieren verschlüsselte Datenmuster mit fortschrittlichen Machine-Learning-Algorithmen',
    'tech.step2.title': 'Musteranalyse',
    'tech.step2.desc': 'Neuronale Netze identifizieren kryptographische Muster und potenzielle Schwachstellen',
    'tech.step3.title': 'Quantenverarbeitung',
    'tech.step3.desc': 'Quantenalgorithmen verarbeiten Millionen von Möglichkeiten gleichzeitig',
    'tech.step4.title': 'Datenwiederherstellung',
    'tech.step4.desc': 'Erfolgreiches Entschlüsseln und Wiederherstellen von Daten mit 99,9% Genauigkeit',
    
    // Services
    'services.title': 'Unsere Dienstleistungen',
    'services.subtitle': 'Fortschrittliche Kryptographie-Analyse für alle wichtigen Plattformen',
    'services.coming-soon': 'Demnächst',
    
    // WhatsApp Service
    'whatsapp.title': 'WhatsApp-Analyse',
    'whatsapp.reviews': 'Benutzerbewertungen',
    'whatsapp.phone-label': 'WhatsApp-Nummer',
    'whatsapp.phone-placeholder': '+49 151 12345678',
    'whatsapp.start': 'Analyse Starten',
    'whatsapp.disclaimer': '⚠️ Bildungssimulator. WhatsApp verwendet E2E-Verschlüsselung, die mathematisch unmöglich zu knacken ist.',
    'whatsapp.analyzing': 'Analyse läuft',
    'whatsapp.phase1': 'Verbindung zur KI',
    'whatsapp.phase2': 'Verschlüsselung analysieren',
    'whatsapp.phase3': 'Daten scannen',
    'whatsapp.phase4': 'Inhalt klassifizieren',
    'whatsapp.phase5': 'Ergebnisse generieren',
    'whatsapp.complete': 'Analyse Abgeschlossen',
    'whatsapp.conversations': 'Gespräche',
    'whatsapp.images': 'Bilder',
    'whatsapp.videos': 'Videos',
    'whatsapp.privacy': 'Inhalt aus Datenschutzgründen unscharf',
    'whatsapp.notice.title': 'Bildungshinweis',
    'whatsapp.notice.text1': 'Dies ist ein Bildungssimulator, der Sicherheitskonzepte demonstriert. WhatsApp verwendet Ende-zu-Ende-Verschlüsselung (E2E), die mathematisch unmöglich zu knacken ist.',
    'whatsapp.notice.text2': 'Es wurden keine echten Daten abgerufen oder kompromittiert. Dies ist rein eine Bildungsübung.',
    'whatsapp.new-analysis': 'Neue Analyse',
    'whatsapp.back': 'Zurück',
    
    // Reviews
    'reviews.title': 'Kundenbewertungen',
    'reviews.subtitle': 'Sehen Sie, was unsere Kunden über unsere Dienstleistungen sagen',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': 'Funktionierte perfekt! Habe alle meine alten Gespräche wiederhergestellt. Erstaunliche Technologie!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Sehr professioneller Service. Das Team war äußerst hilfsbereit und das Ergebnis übertraf meine Erwartungen.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Beeindruckende KI-Technologie. Ich konnte alte Fotos wiederherstellen, die ich für immer verloren glaubte.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Ausgezeichneter Gmail-Wiederherstellungsservice. Habe wichtige E-Mails von vor Jahren wiederhergestellt.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Habe alle meine Instagram-Fotos wiederhergestellt. Der Prozess war schnell und sicher. Sehr zu empfehlen!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'Konnte auf alte Facebook-Nachrichten zugreifen. Sehr kompetentes und aufmerksames Team.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'WhatsApp-Service funktionierte perfekt. Habe Gespräche von vor über 2 Jahren wiederhergestellt!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'Telegram-Analyse war sehr effizient. Spitzentechnologie mit beeindruckenden Ergebnissen.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Ausgezeichnetes Preis-Leistungs-Verhältnis. Habe wichtige WhatsApp-Daten schnell und sicher wiederhergestellt.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Führender Anbieter von KI-gestützten Kryptographie-Analyse- und Wiederherstellungslösungen.',
    'footer.quick-links': 'Schnelllinks',
    'footer.services': 'Dienstleistungen',
    'footer.contact': 'Kontakt',
    'footer.copyright': '© 2024 Redline Systems AI. Alle Rechte vorbehalten.',
  },
  
  'zh': {
    // Header
    'nav.home': '首页',
    'nav.team': '团队',
    'nav.technology': '技术',
    'nav.services': '服务',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': '最先进的加密破解和账户恢复技术',
    'hero.description': '我们能够破解任何加密系统并恢复您所有社交媒体账户的访问权限！我们的量子AI技术被全球政府和情报机构使用，保证99.9%的数据恢复成功率。使用保护国家的同样技术恢复您丢失的账户！',
    'hero.stat1': '成功率',
    'hero.stat2': '计算能力',
    'hero.stat3': '账户已恢复',
    
    // Team
    'team.title': '世界级团队',
    'team.subtitle': '我们的专家曾在世界领先的科技公司和研究机构工作',
    'team.role.cto': '首席技术官',
    'team.role.head-ai': 'AI研究主管',
    'team.role.senior-crypto': '高级密码学工程师',
    'team.role.chief-security': '首席安全架构师',
    'team.role.lead-quantum': '首席量子计算专家',
    'team.bio.rajesh': '前谷歌首席AI研究员。麻省理工学院量子计算博士。15年以上密码学经验。',
    'team.bio.priya': '前微软AI部门。专注于神经网络和机器学习。发表50多篇研究论文。',
    'team.bio.vikram': '曾任职于亚马逊网络服务。RSA和AES加密算法专家。12年经验。',
    'team.bio.wei': '前阿里巴巴云安全负责人。清华大学网络安全博士。18年从业经验。',
    'team.bio.li': '前华为研究员。量子密码学先驱。多项量子算法专利。',
    
    // Technology
    'tech.title': '我们的技术',
    'tech.subtitle': '尖端AI和量子计算基础设施，推动突破性密码分析',
    'tech.ai.title': '先进AI模型',
    'tech.ai.desc': '在数十亿加密模式上训练的专有神经网络',
    'tech.quantum.title': '量子计算',
    'tech.quantum.desc': '利用量子算法实现指数级处理速度',
    'tech.distributed.title': '分布式计算',
    'tech.distributed.desc': '全球数据中心10PB计算能力',
    'tech.pattern.title': '模式识别',
    'tech.pattern.desc': '识别密码学漏洞的ML模型',
    'tech.gpu.title': 'GPU加速',
    'tech.gpu.desc': '数千个GPU并行工作以实现最高效率',
    'tech.cloud.title': '云基础设施',
    'tech.cloud.desc': '处理数百万请求的可扩展架构',
    'tech.how.title': '工作原理',
    'tech.step1.title': '数据采集',
    'tech.step1.desc': '我们的AI系统使用先进的机器学习算法分析加密数据模式',
    'tech.step2.title': '模式分析',
    'tech.step2.desc': '神经网络识别密码模式和潜在漏洞',
    'tech.step3.title': '量子处理',
    'tech.step3.desc': '量子算法同时处理数百万种可能性',
    'tech.step4.title': '数据恢复',
    'tech.step4.desc': '成功解密和恢复数据，准确率达99.9%',
    
    // Services
    'services.title': '我们的服务',
    'services.subtitle': '所有主要平台的高级密码分析',
    'services.coming-soon': '即将推出',
    
    // WhatsApp Service
    'whatsapp.title': 'WhatsApp分析',
    'whatsapp.reviews': '用户评价',
    'whatsapp.phone-label': 'WhatsApp号码',
    'whatsapp.phone-placeholder': '+86 138 0000 0000',
    'whatsapp.start': '开始分析',
    'whatsapp.disclaimer': '⚠️ 教育模拟器。WhatsApp使用数学上无法破解的E2E加密。',
    'whatsapp.analyzing': '分析进行中',
    'whatsapp.phase1': '连接AI',
    'whatsapp.phase2': '分析加密',
    'whatsapp.phase3': '扫描数据',
    'whatsapp.phase4': '分类内容',
    'whatsapp.phase5': '生成结果',
    'whatsapp.complete': '分析完成',
    'whatsapp.conversations': '对话',
    'whatsapp.images': '图片',
    'whatsapp.videos': '视频',
    'whatsapp.privacy': '内容已模糊处理以保护隐私',
    'whatsapp.notice.title': '教育声明',
    'whatsapp.notice.text1': '这是一个演示安全概念的教育模拟器。WhatsApp使用端到端加密(E2E)，数学上无法破解。',
    'whatsapp.notice.text2': '没有访问或泄露任何真实数据。这纯粹是一个教育练习。',
    'whatsapp.new-analysis': '新分析',
    'whatsapp.back': '返回',
    
    // Reviews
    'reviews.title': '客户评价',
    'reviews.subtitle': '看看我们的客户对我们服务的评价',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': '完美运行！恢复了我所有的旧对话。令人惊叹的技术！',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': '非常专业的服务。团队非常乐于助人，结果超出了我的预期。',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': '令人印象深刻的AI技术。我成功恢复了我以为永远丢失的旧照片。',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': '出色的Gmail恢复服务。恢复了多年前的重要电子邮件。',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': '恢复了我所有的Instagram照片。过程快速安全。强烈推荐！',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': '成功访问了旧的Facebook消息。非常称职和细心的团队。',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'WhatsApp服务完美运行。恢复了2年前的对话！',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'Telegram分析非常高效。尖端技术，结果令人印象深刻。',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': '性价比极高。快速安全地恢复了重要的WhatsApp数据。',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'AI驱动的密码分析和恢复解决方案的领先提供商。',
    'footer.quick-links': '快速链接',
    'footer.services': '服务',
    'footer.contact': '联系方式',
    'footer.copyright': '© 2024 Redline Systems AI. 保留所有权利。',
  },
  
  'ja': {
    // Header
    'nav.home': 'ホーム',
    'nav.team': 'チーム',
    'nav.technology': '技術',
    'nav.services': 'サービス',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': '暗号解読とアカウント復旧における最先端技術',
    'hero.description': 'あらゆる暗号化システムを解読し、すべてのソーシャルメディアアカウントへのアクセスを復旧できます！世界中の政府や諜報機関が使用する当社の量子AI技術は、データ復旧において99.9%の成功率を保証します。国家を守る技術で失われたアカウントを取り戻しましょう！',
    'hero.stat1': '成功率',
    'hero.stat2': '計算能力',
    'hero.stat3': 'アカウント復旧数',
    
    // Team
    'team.title': '世界クラスのチーム',
    'team.subtitle': '当社の専門家は、世界をリードするテクノロジー企業や研究機関で働いてきました',
    'team.role.cto': '最高技術責任者',
    'team.role.head-ai': 'AI研究責任者',
    'team.role.senior-crypto': 'シニア暗号エンジニア',
    'team.role.chief-security': 'チーフセキュリティアーキテクト',
    'team.role.lead-quantum': 'リード量子コンピューティングスペシャリスト',
    'team.bio.rajesh': '元GoogleリードAI研究者。MIT量子コンピューティング博士。暗号学15年以上の経験。',
    'team.bio.priya': '元Microsoft AI部門。ニューラルネットワークと機械学習を専門。50以上の研究論文を発表。',
    'team.bio.vikram': '元Amazon Web Services。RSAおよびAES暗号化アルゴリズムの専門家。12年の経験。',
    'team.bio.wei': '元Alibabaクラウドセキュリティリーダー。清華大学サイバーセキュリティ博士。18年の実績。',
    'team.bio.li': '元Huawei研究員。量子暗号学のパイオニア。量子アルゴリズムの複数の特許。',
    
    // Technology
    'tech.title': '私たちの技術',
    'tech.subtitle': '画期的な暗号解析を実現する最先端のAIと量子コンピューティングインフラストラクチャ',
    'tech.ai.title': '高度なAIモデル',
    'tech.ai.desc': '数十億の暗号化パターンで訓練された独自のニューラルネットワーク',
    'tech.quantum.title': '量子コンピューティング',
    'tech.quantum.desc': '指数関数的な処理速度のための量子アルゴリズムの活用',
    'tech.distributed.title': '分散コンピューティング',
    'tech.distributed.desc': 'グローバルデータセンターにわたる10ペタバイトの計算能力',
    'tech.pattern.title': 'パターン認識',
    'tech.pattern.desc': '暗号の脆弱性を特定するMLモデル',
    'tech.gpu.title': 'GPUアクセラレーション',
    'tech.gpu.desc': '最大効率のために並列動作する数千のGPU',
    'tech.cloud.title': 'クラウドインフラストラクチャ',
    'tech.cloud.desc': '数百万のリクエストを処理するスケーラブルなアーキテクチャ',
    'tech.how.title': '仕組み',
    'tech.step1.title': 'データ取得',
    'tech.step1.desc': '当社のAIシステムは、高度な機械学習アルゴリズムを使用して暗号化されたデータパターンを分析します',
    'tech.step2.title': 'パターン分析',
    'tech.step2.desc': 'ニューラルネットワークが暗号パターンと潜在的な脆弱性を特定',
    'tech.step3.title': '量子処理',
    'tech.step3.desc': '量子アルゴリズムが数百万の可能性を同時に処理',
    'tech.step4.title': 'データ復旧',
    'tech.step4.desc': '99.9%の精度でデータの復号化と復旧に成功',
    
    // Services
    'services.title': '私たちのサービス',
    'services.subtitle': 'すべての主要プラットフォームの高度な暗号解析',
    'services.coming-soon': '近日公開',
    
    // WhatsApp Service
    'whatsapp.title': 'WhatsApp分析',
    'whatsapp.reviews': 'ユーザーレビュー',
    'whatsapp.phone-label': 'WhatsApp番号',
    'whatsapp.phone-placeholder': '+81 90-1234-5678',
    'whatsapp.start': '分析を開始',
    'whatsapp.disclaimer': '⚠️ 教育シミュレーター。WhatsAppは数学的に解読不可能なE2E暗号化を使用しています。',
    'whatsapp.analyzing': '分析中',
    'whatsapp.phase1': 'AIに接続中',
    'whatsapp.phase2': '暗号化を分析中',
    'whatsapp.phase3': 'データをスキャン中',
    'whatsapp.phase4': 'コンテンツを分類中',
    'whatsapp.phase5': '結果を生成中',
    'whatsapp.complete': '分析完了',
    'whatsapp.conversations': '会話',
    'whatsapp.images': '画像',
    'whatsapp.videos': '動画',
    'whatsapp.privacy': 'プライバシーのためコンテンツをぼかしています',
    'whatsapp.notice.title': '教育的通知',
    'whatsapp.notice.text1': 'これはセキュリティ概念を示す教育シミュレーターです。WhatsAppは数学的に解読不可能なエンドツーエンド暗号化(E2E)を使用しています。',
    'whatsapp.notice.text2': '実際のデータにアクセスまたは侵害されていません。これは純粋に教育的な演習です。',
    'whatsapp.new-analysis': '新しい分析',
    'whatsapp.back': '戻る',
    
    // Reviews
    'reviews.title': 'お客様のレビュー',
    'reviews.subtitle': '当社のサービスについてお客様の声をご覧ください',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': '完璧に機能しました！古い会話をすべて復元できました。素晴らしい技術です！',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': '非常にプロフェッショナルなサービス。チームは非常に親切で、結果は期待を上回りました。',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': '印象的なAI技術。永遠に失われたと思っていた古い写真を復元できました。',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': '優れたGmail復旧サービス。何年も前の重要なメールを復元しました。',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Instagramの写真をすべて復元しました。プロセスは迅速で安全でした。お勧めします！',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': '古いFacebookメッセージにアクセスできました。非常に有能で気配りのあるチームです。',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'WhatsAppサービスは完璧に機能しました。2年以上前の会話を復元しました！',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'Telegram分析は非常に効率的でした。最先端技術で印象的な結果が得られました。',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': '優れたコストパフォーマンス。重要なWhatsAppデータを迅速かつ安全に復元しました。',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'AI駆動の暗号解析および復旧ソリューションの主要プロバイダー。',
    'footer.quick-links': 'クイックリンク',
    'footer.services': 'サービス',
    'footer.contact': '連絡先',
    'footer.copyright': '© 2024 Redline Systems AI. 全著作権所有。',
  },
  
  'ru': {
    // Header
    'nav.home': 'Главная',
    'nav.team': 'Команда',
    'nav.technology': 'Технология',
    'nav.services': 'Услуги',
    
    // Hero
    'hero.title': 'Redline Systems AI',
    'hero.subtitle': 'Военная Технология Взлома Шифрования и Полного Восстановления Аккаунтов',
    'hero.description': 'Разработанная ЛУЧШИМИ программистами и специалистами по ИИ мирового рынка, наша квантовая технология способна взломать ЛЮБУЮ существующую систему шифрования. Нам нужен ТОЛЬКО ваш @email, имя пользователя ИЛИ номер телефона для восстановления 100% доступа! Используемая правительствами и глобальными спецслужбами, мы гарантируем 99.9% успеха в ПОЛНОМ восстановлении ваших аккаунтов. Верните утраченный доступ с той же военной технологией, которая защищает целые государства!',
    'hero.requirement': '✓ Нам нужен ТОЛЬКО: @Email, Имя Пользователя ИЛИ Номер Телефона',
    'hero.stat1': 'Уровень Успеха',
    'hero.stat2': 'Вычислительная Мощность',
    'hero.stat3': 'Аккаунтов Восстановлено',
    
    // Team
    'team.title': 'Команда Мирового Класса',
    'team.subtitle': 'Наши эксперты работали в ведущих технологических компаниях и исследовательских учреждениях мира',
    'team.role.cto': 'Технический Директор',
    'team.role.head-ai': 'Руководитель Исследований ИИ',
    'team.role.senior-crypto': 'Старший Инженер по Криптографии',
    'team.role.chief-security': 'Главный Архитектор Безопасности',
    'team.role.lead-quantum': 'Ведущий Специалист по Квантовым Вычислениям',
    'team.bio.rajesh': 'Бывший ведущий исследователь ИИ в Google. PhD по квантовым вычислениям из MIT. Более 15 лет в криптографии.',
    'team.bio.priya': 'Бывший отдел ИИ Microsoft. Специализируется на нейронных сетях и машинном обучении. Опубликовано более 50 исследовательских работ.',
    'team.bio.vikram': 'Ранее в Amazon Web Services. Эксперт по алгоритмам шифрования RSA и AES. 12 лет опыта.',
    'team.bio.wei': 'Бывший руководитель облачной безопасности Alibaba. PhD по кибербезопасности из Университета Цинхуа. 18 лет в области.',
    'team.bio.li': 'Бывший исследователь Huawei. Пионер в квантовой криптографии. Множественные патенты в квантовых алгоритмах.',
    
    // Technology
    'tech.title': 'Наша Технология',
    'tech.subtitle': 'Передовая инфраструктура ИИ и квантовых вычислений для революционного криптографического анализа',
    'tech.ai.title': 'Продвинутые Модели ИИ',
    'tech.ai.desc': 'Собственные нейронные сети, обученные на миллиардах шаблонов шифрования',
    'tech.quantum.title': 'Квантовые Вычисления',
    'tech.quantum.desc': 'Использование квантовых алгоритмов для экспоненциальной скорости обработки',
    'tech.distributed.title': 'Распределенные Вычисления',
    'tech.distributed.desc': '10 петабайт вычислительной мощности в глобальных центрах обработки данных',
    'tech.pattern.title': 'Распознавание Паттернов',
    'tech.pattern.desc': 'ML модели, которые идентифицируют криптографические уязвимости',
    'tech.gpu.title': 'Ускорение GPU',
    'tech.gpu.desc': 'Тысячи GPU работают параллельно для максимальной эффективности',
    'tech.cloud.title': 'Облачная Инфраструктура',
    'tech.cloud.desc': 'Масштабируемая архитектура, обрабатывающая миллионы запросов',
    'tech.how.title': 'Как Это Работает',
    'tech.step1.title': 'Сбор Данных',
    'tech.step1.desc': 'Наши системы ИИ анализируют зашифрованные шаблоны данных с использованием передовых алгоритмов машинного обучения',
    'tech.step2.title': 'Анализ Паттернов',
    'tech.step2.desc': 'Нейронные сети идентифицируют криптографические паттерны и потенциальные уязвимости',
    'tech.step3.title': 'Квантовая Обработка',
    'tech.step3.desc': 'Квантовые алгоритмы обрабатывают миллионы возможностей одновременно',
    'tech.step4.title': 'Восстановление Данных',
    'tech.step4.desc': 'Успешная расшифровка и восстановление данных с точностью 99,9%',
    
    // Services
    'services.title': 'Наши Услуги',
    'services.subtitle': 'Передовой криптографический анализ для всех основных платформ',
    'services.coming-soon': 'Скоро',
    
    // WhatsApp Service
    'whatsapp.title': 'Анализ WhatsApp',
    'whatsapp.reviews': 'Отзывы Пользователей',
    'whatsapp.phone-label': 'Номер WhatsApp',
    'whatsapp.phone-placeholder': '+7 (999) 123-4567',
    'whatsapp.start': 'Начать Анализ',
    'whatsapp.disclaimer': '⚠️ Образовательный симулятор. WhatsApp использует шифрование E2E, которое математически невозможно взломать.',
    'whatsapp.analyzing': 'Анализ в Процессе',
    'whatsapp.phase1': 'Подключение к ИИ',
    'whatsapp.phase2': 'Анализ Шифрования',
    'whatsapp.phase3': 'Сканирование Данных',
    'whatsapp.phase4': 'Классификация Контента',
    'whatsapp.phase5': 'Генерация Результатов',
    'whatsapp.complete': 'Анализ Завершен',
    'whatsapp.conversations': 'Беседы',
    'whatsapp.images': 'Изображения',
    'whatsapp.videos': 'Видео',
    'whatsapp.privacy': 'Контент размыт для конфиденциальности',
    'whatsapp.notice.title': 'Образовательное Уведомление',
    'whatsapp.notice.text1': 'Это образовательный симулятор, демонстрирующий концепции безопасности. WhatsApp использует сквозное шифрование (E2E), которое математически невозможно взломать.',
    'whatsapp.notice.text2': 'Никакие реальные данные не были доступны или скомпрометированы. Это чисто образовательное упражнение.',
    'whatsapp.new-analysis': 'Новый Анализ',
    'whatsapp.back': 'Назад',
    
    // Reviews
    'reviews.title': 'Отзывы Клиентов',
    'reviews.subtitle': 'Посмотрите, что говорят наши клиенты о наших услугах',
    'reviews.user1.name': 'Carlos Mendes',
    'reviews.user1.text': 'Работало идеально! Восстановил все мои старые разговоры. Потрясающая технология!',
    'reviews.user2.name': 'Ana Paula Silva',
    'reviews.user2.text': 'Очень профессиональный сервис. Команда была чрезвычайно полезной, и результат превзошел мои ожидания.',
    'reviews.user3.name': 'Roberto Santos',
    'reviews.user3.text': 'Впечатляющая технология ИИ. Мне удалось восстановить старые фотографии, которые я считал потерянными навсегда.',
    'reviews.user4.name': 'Maria Oliveira',
    'reviews.user4.text': 'Отличный сервис восстановления Gmail. Восстановил важные письма многолетней давности.',
    'reviews.user5.name': 'João Pedro',
    'reviews.user5.text': 'Восстановил все мои фотографии из Instagram. Процесс был быстрым и безопасным. Рекомендую!',
    'reviews.user6.name': 'Fernanda Costa',
    'reviews.user6.text': 'Удалось получить доступ к старым сообщениям Facebook. Очень компетентная и внимательная команда.',
    'reviews.user7.name': 'Lucas Almeida',
    'reviews.user7.text': 'Сервис WhatsApp работал идеально. Восстановил разговоры более чем двухлетней давности!',
    'reviews.user8.name': 'Juliana Martins',
    'reviews.user8.text': 'Анализ Telegram был очень эффективным. Передовая технология с впечатляющими результатами.',
    'reviews.user9.name': 'Rafael Souza',
    'reviews.user9.text': 'Отличное соотношение цены и качества. Быстро и безопасно восстановил важные данные WhatsApp.',
    
    // Footer
    'footer.company': 'Redline Systems AI',
    'footer.description': 'Ведущий поставщик решений для криптографического анализа и восстановления на основе ИИ.',
    'footer.quick-links': 'Быстрые Ссылки',
    'footer.services': 'Услуги',
    'footer.contact': 'Контакт',
    'footer.copyright': '© 2024 Redline Systems AI. Все права защищены.',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pt-BR')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLang = localStorage.getItem('language') as Language
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang)
    } else {
      // Detect browser language
      const browserLang = navigator.language
      if (translations[browserLang as Language]) {
        setLanguageState(browserLang as Language)
      } else if (browserLang.startsWith('pt')) {
        setLanguageState('pt-BR')
      } else if (browserLang.startsWith('en')) {
        setLanguageState('en')
      }
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
